server:
  info:
    app_title: CMBF Sample Server
    app_name: cmbf_sample_server

plugins:
  system:
    root_log:
      name: sample-server-system-log
      level: trace
  mongodb:
    dbs:
      - name: MAIN
        uri: mongodb://$MONGODB_HOST:27017/cmbf_main
      - name: ARCHIVE
        uri: mongodb://$MONGODB_HOST:27017/cmbf_archive

MONGODB_HOST: localhost
PORT: 3000
ADMIN_PORT: 3001
